// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7CbvIXbOwac8GI721xf-XqPaXrLheQY',
    appId: '1:986983591563:web:e2aa1a73d2b1d7e4f9ae8e',
    messagingSenderId: '986983591563',
    projectId: 'bloc-test-flutter-1234987',
    authDomain: 'bloc-test-flutter-1234987.firebaseapp.com',
    databaseURL: 'https://bloc-test-flutter-1234987-default-rtdb.firebaseio.com',
    storageBucket: 'bloc-test-flutter-1234987.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGS3njSfaSqa3cnTS2KTSL_HNxKDQsR4U',
    appId: '1:986983591563:android:2b1754ca0a5371e4f9ae8e',
    messagingSenderId: '986983591563',
    projectId: 'bloc-test-flutter-1234987',
    databaseURL: 'https://bloc-test-flutter-1234987-default-rtdb.firebaseio.com',
    storageBucket: 'bloc-test-flutter-1234987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROxmapn13zPMafgN6gmBx1u0-sRnm6uo',
    appId: '1:986983591563:ios:c09450d318220b9cf9ae8e',
    messagingSenderId: '986983591563',
    projectId: 'bloc-test-flutter-1234987',
    databaseURL: 'https://bloc-test-flutter-1234987-default-rtdb.firebaseio.com',
    storageBucket: 'bloc-test-flutter-1234987.appspot.com',
    androidClientId: '986983591563-js8ac53heoq5fhjua6vtmgao5ujd49db.apps.googleusercontent.com',
    iosClientId: '986983591563-3nl2qodti0edflbh9vl1tskf11i9vec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastapiProject',
  );
}
